# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0

type: object
description: Thing validation config.
properties:
  enforce:
    type: object
    properties:
      enforceThingDescriptionModification:
        type: boolean
      attributes:
        type: boolean
      inboxMessagesInput:
        type: boolean
      inboxMessagesOutput:
        type: boolean
      outboxMessages:
        type: boolean
  forbid:
    type: object
    properties:
      thingDescriptionDeletion:
        type: boolean
      nonModeledAttributes:
        type: boolean
      nonModeledInboxMessages:
        type: boolean
      nonModeledOutboxMessages:
        type: boolean 