# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0

type: object
description: WoT validation configuration object.
properties:
  configId:
    type: string
    description: The unique ID of the config.
  enabled:
    type: boolean
    description: Whether WoT validation is enabled globally. Defaults to true if not specified.
  log-warning-instead-of-failing-api-calls:
    type: boolean
  thing:
    $ref: 'thingValidationConfig.yml'
  feature:
    $ref: 'featureValidationConfig.yml'
  dynamic-config:
    type: array
    items:
      $ref: 'dynamicValidationConfig.yml'
  revision:
    type: integer
    format: int64
  created:
    type: string
    format: date-time
  modified:
    type: string
    format: date-time
  deleted:
    type: boolean
  metadata:
    type: object
required:
  - configId
  - thing
  - feature 