# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
get:
  summary: Retrieve the configuration at the specified path parameter
  description: |-
    It is recommended to not omit the query parameter path.
    Otherwise, the full configurations of all services are aggregated in the response, which can become megabytes big.
  security:
    - DevOpsBasic: []
    - DevOpsBearer: []
  tags:
    - Devops
  parameters:
    - $ref: '../../parameters/pathParam.yml'
  responses:
    '200':
      description: |-
        Return the configuration at the path
      content:
        application/json:
          schema:
            $ref: '../../schemas/config/retrieveConfig.yml'
    '401':
      description: The request could not be completed due to missing authentication.
      content:
        text/plain:
          schema:
            $ref: '../../schemas/errors/textUnauthorizeError.yml'
