# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0

parameters:
  - name: scopeId
    in: path
    required: true
    schema:
      type: string
get:
  summary: Get a dynamic WoT validation config section by scopeId
  tags:
    - Devops
  security:
    - DevOpsBasic: []
    - DevOpsBearer: []
  responses:
    '200':
      $ref: '../../responses/wotValidationConfig/dynamicValidationConfigResponse.yml'
    '404':
      description: Not found
put:
  summary: Create or update a dynamic WoT validation config section
  tags: [Devops]
  security:
    - DevOpsBasic: []
    - DevOpsBearer: []
  requestBody:
    $ref: '../../requests/wotValidationConfig/dynamicValidationConfigRequest.yml'
  responses:
    '204':
      description: Updated dynamic config section
delete:
  summary: Delete a dynamic WoT validation config section
  tags:
    - Devops
  security:
    - DevOpsBasic: []
    - DevOpsBearer: []
  responses:
    '204':
      description: Deleted successfully
    '404':
      description: Not found 