# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0

get:
  summary: List all dynamic WoT validation config sections
  tags:
    - Devops
  security:
    - DevOpsBasic: []
    - DevOpsBearer: []
  responses:
    '200':
      description: List of dynamic config sections
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../../schemas/wotValidationConfig/dynamicValidationConfig.yml'