# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
get:
  summary: Retrieve all currently configured log levels
  description: Return configured log level for all ditto cluster pod
  security:
    - DevOpsBasic: []
    - DevOpsBearer: []
  tags:
    - Devops
  parameters:
    - $ref: '../../parameters/loggingFieldsQueryParam.yml'
  responses:
    '200':
      description: |-
        Return The current value of logging level
      content:
        application/json:
          schema:
            $ref: '../../schemas/logging/retrieveLoggingConfig.yml'
    '401':
      description: The request could not be completed due to missing authentication.
      content:
        text/plain:
          schema:
            $ref: '../../schemas/errors/textUnauthorizeError.yml'
put:
  summary: Update log levels
  description: |-
    Modify log level for eatch pods menaged
  security:
    - DevOpsBasic: []
    - DevOpsBearer: []
  tags:
    - Devops
  requestBody:
    description: Fields to update level log for each pods
    required: true
    content:
      application/json:
        schema:
          $ref: '../../schemas/logging/loggingUpdateFields.yml'
        example: |-
          {
            "level": "info",
            "logger": "org.apache.pekko.actor.CoordinatedShutdown"
          }
  responses:
    '201':
      $ref: '../../responses/successUpdateLogLevel.yml'
    '401':
      description: The request could not be completed due to missing authentication.
      content:
        text/plain:
          schema:
            $ref: '../../schemas/errors/textUnauthorizeError.yml'


