# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
type: object
description:  Return the configuration at the path ditto.info
properties:
  type:
    type: string
    description: devops.responses:ResultConfig
  status:
    type: integer
    description: The HTTP status
  config:
    type: object
    description: name of service
    properties:
      env:
        items:
          type: string
        properties:
          PATH:
            type: string
      service:
        items:
          type: string
        properties:
          instance-index:
            type: integer
          service-name:
            type: string
      vm-args:
        items:
          type: string

